import "./globals.css";

import { Providers } from "@/components/providers/root";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const cookie = cookies().toString();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers cookies={cookie}>{children}</Providers>
      </body>
    </html>
  );
}
